name: Tests

on: [ 'push', 'pull_request' ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ '8.1','8.2','8.3','8.4' ]

    name: Tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Aspell
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y aspell aspell-en

      - name: Cache Dependencies PHP
        id: php-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: dependencies-php-composer-${{ hashFiles('composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: xdebug

      - name: Set up Node & NPM
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Setup Problem Matches
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install PHP dependencies
        if: steps.php-cache.outputs.cache-hit != 'true'
        run: composer install --no-interaction --no-progress --ansi

      - name: Get NPM cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Cache dependencies
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Build dependencies
        run: npm run build

      - name: Tests
        run: composer test

      # Failure Notification
      - name: Notify on Failure
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
               "content": "🚨 Workflow **failed** for **${{ github.repository }}**!",
               "embeds": [
                 {
                   "title": "Workflow Failure (PHP ${{ matrix.php }})",
                   "description": "Branch: `${{ github.ref_name }}`\nTriggeredBy: `${{ github.triggering_actor}}`\nCommit: `${{ github.sha}}`",
                   "color": 16711680
                 }
               ]
             }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

      # Success Notification
      - name: Notify on Success
        if: success() && always()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "content": "✅ Workflow **succeeded** for **${{ github.repository }}**!",
                "embeds": [
                  {
                    "title": "Success (PHP ${{ matrix.php }})",
                    "description": "Branch: `${{ github.ref_name }}`\nTriggeredBy: `${{ github.triggering_actor}}`\nCommit: `${{ github.sha}}`",
                    "color": 65280
                  }
                ]
              }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}